"""Added tables

Revision ID: c19a9b0c2e92
Revises: 
Create Date: 2023-04-18 22:56:51.570138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19a9b0c2e92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_id'), 'colors', ['id'], unique=False)
    op.create_table('items',
    sa.Column('nm_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('site_brand_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedbacks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nm_id')
    )
    op.create_index(op.f('ix_items_nm_id'), 'items', ['nm_id'], unique=False)
    op.create_table('association_table',
    sa.Column('items_id', sa.Integer(), nullable=True),
    sa.Column('colors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colors_id'], ['colors.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['items_id'], ['items.nm_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.UniqueConstraint('items_id', 'colors_id', name='items_colors')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    op.drop_index(op.f('ix_items_nm_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_colors_id'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
